var guitars = [
  {
    _id: "1",
    name: "American Standard Stratocaster",
    color: "Yellow",
    image: "/images/strat.jpg",
    brand: "Fender",
    category: "Blues",
    price: 1000,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Les Paul SG",
    color: "Ebony",
    image: "/images/gibson-sg-ebony.jpg",
    brand: "Gibson",
    category: "Rock",
    price: 1200,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Les Paul Standard",
    color: "Vintage Sunburst",
    image: "/images/les-paul.jpg",
    brand: "Gibson",
    category: "Rock",
    price: 1400,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Custom 24",
    color: "Blue",
    image: "/images/prs-custom-24.jpg",
    brand: "PRS",
    category: "Blues",
    price: 1000,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Byrds",
    color: "Cherry Sunburst",
    image: "/images/rickenbecker.jpg",
    brand: "Rickenbecker",
    category: "Jingle Jangle",
    price: 1999,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "American Standard Telecaster",
    color: "Wood",
    image: "/images/tele.jpg",
    brand: "Fender",
    category: "Blues",
    price: 1199,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "100 Series Acoustic",
    color: "Vintage Natural",
    image: "/images/taylor.jpg",
    brand: "Taylor",
    category: "All",
    price: 799,
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
];

module.exports.guitars = guitars;
